sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t tarunkumar19944/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true tarunkumar19944/docker-react npm run test
